app:
  name: 'kick chat listen '
  version: '1.0.0'
  description: 'kick channel  chat listen'

server:
  port: 8080
  host: 'localhost'

postgres:
  port: 5432
  user: 'myuser'
  password: 'mypassword'
  db: 'kickdb'
  host: 'localhost'
  image: kick-chat-postgres
